### ISSUE TITLE
Amélioration

### ISSUE THREAD

**Issue by bilAlid** [mrbahadoor/symfony-test2#1]
Bonjour @mrbahadoor 

Merci pour votre travail de qualité !
Je viens de faire la review et c'est du bon travail pour continuer.

Sur le même projet, pouvez-vous apporter les changements suivants (il faut une pull-request par changement):
- [x] Supprimer ApiPlatform
- [x] Utiliser PHP8 et les annotations avec `#`

@marouanePM

**Comment by mrbahadoor** [comment]
> Bonjour @mrbahadoor
> 
> Merci pour votre travail de qualité ! Je viens de faire la review et c'est du bon travail pour continuer.
> 
> Sur le même projet, pouvez-vous apporter les changements suivants (il faut une pull-request par changement):
> 
>     * [x]  Supprimer ApiPlatform
> 
>     * [x]  Utiliser PHP8 et les annotations avec `#`
> 
> 
> @MarouanePM

**Comment by mrbahadoor** [comment]
Bonsoir @bilAlid

Merci pour ce projet ! 

Veuillez noter que les changements sont faits. J'ai déjà fait un merge sur le premier pull-request.
